K8s: Multi-interface support fixes

diff --git a/scripts/k8s/k8s-common b/scripts/k8s/k8s-common
--- a/scripts/k8s/k8s-common
+++ b/scripts/k8s/k8s-common
@@ -52,22 +52,37 @@ function f_wait_for_dns() {
 # Construct JVM_OPTS with dynamic interface lookup
 function f_set_jvm_opts() {
 
-  # Look up the interface we're supposed to use.
-  if [[ "${POD_NAME}" == "aeron-benchmark-0" ]]
-  then
-    LOCAL_IP="$( host "${NODE0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
-  elif [[ "${POD_NAME}" == "aeron-benchmark-1" ]]
-  then
-    LOCAL_IP="$( host "${NODE1_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
-  else
-    echo "Could not resolve IP for POD ${POD_NAME}"
+
+  # If this is not a DPDK test...
+  if [[ "${BENCHMARK_TYPE}" =~ dpdk$ ]]
+    then
+      # Don't select an interface
+      SELECT_INTERFACE=""
+    else
+      # Look up the interface we're supposed to use.
+      case ${POD_NAME} in
+        aeron-benchmark-0)
+          LOCAL_IP="$( host "${NODE0_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+          ;;
+        aeron-benchmark-1)
+          LOCAL_IP="$( host "${NODE1_ADDRESS}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' )"
+          ;;
+        *)
+          echo "Error: Could not resolve IP for POD ${POD_NAME}"
+          exit 1
+          ;;
+      esac
+      # Specifically select the interface to use.
+      SELECT_INTERFACE="|interface=${LOCAL_IP}/32"
+
   fi
 
   export JVM_OPTS="-Duk.co.real_logic.benchmarks.remote.output.directory=/dev/shm/results \
 -Duk.co.real_logic.benchmarks.aeron.remote.embedded.media.driver=false \
--Duk.co.real_logic.benchmarks.aeron.remote.source.channel=aeron:udp?endpoint=${NODE1_ADDRESS:? Could not find NODE1_ADDRESS}:13000|interface=${LOCAL_IP}/32 \
--Duk.co.real_logic.benchmarks.aeron.remote.destination.channel=aeron:udp?endpoint=${NODE0_ADDRESS:? Could not find NODE0_ADDRESS}:13001|interface=${LOCAL_IP}/32"
+-Duk.co.real_logic.benchmarks.aeron.remote.source.channel=aeron:udp?endpoint=${NODE1_ADDRESS:? Could not find NODE1_ADDRESS}:13000${SELECT_INTERFACE} \
+-Duk.co.real_logic.benchmarks.aeron.remote.destination.channel=aeron:udp?endpoint=${NODE0_ADDRESS:? Could not find NODE0_ADDRESS}:13001${SELECT_INTERFACE}"
 }
+
 #####################################################################################
 # Things to run *before* a benchmark client runs
 function f_benchmark_pre(){
